# Generated by Django 5.1.1 on 2026-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_accepted_at_booking_arrived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='response_timeout_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
