# Generated by Django 5.1.1 on 2026-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_response_timeout_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='response_timeout_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
