# Generated by Django 5.1.1 on 2026-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smsnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(default='+255 786 225 687', max_length=40)),
                ('backup_sender_number', models.CharField(blank=True, max_length=40)),
                ('backend', models.CharField(default='console', max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_token', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
