# Generated by Django 5.2.4 on 2026-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_published_service_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
