# Generated by Django 4.2 on 2026-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_online_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='birth_certificate',
            field=models.FileField(blank=True, help_text='Birth certificate (PDF)', null=True, upload_to='provider_birth_certs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='cv_document',
            field=models.FileField(blank=True, help_text='CV/Resume (PDF)', null=True, upload_to='provider_cvs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_certificate',
            field=models.FileField(blank=True, help_text='Service qualification certificate (PDF)', null=True, upload_to='provider_certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='NIN or National ID', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nin_document',
            field=models.FileField(blank=True, null=True, upload_to='nin_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
