# Generated by Django 4.2 on 2026-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_providerprofile_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_category',
            field=models.CharField(blank=True, help_text='Service category', max_length=50),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_name',
            field=models.CharField(blank=True, help_text='Name of the service offered', max_length=150),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/about'),
        ),
    ]
