# Generated by Django 5.2.4 on 2026-04-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tigo', 'Tigo Pesa'), ('card', 'Bank Card')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('provider_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
